### ISSUE TITLE
Block explorer does not show Sapling inputs+outputs

### ISSUE THREAD

**Issue by leto** [btcz/bitcoinz#61]
I was doing some research on BTCZ transactions and upon looking at:

https://explorer.btcz.rocks/tx/91d53d7d9163926c60f66d4be150f550798736b99eb0f5599aa2121b4304e456

it seems it is a z2z and has no joinsplits because it's not sprout, but shielded spends and outputs are not being shown. Your insight explorer probably needs to be updated to understand Sapling

**Comment by MarcelusCH** [comment]
Hi Leto, this issue is related to the insight explorer and should be posted here : https://github.com/bitcoinz-dev-tools/insight-ui-btcz

If you check again, you will remark that its now solved with the Insight Explorer experimental feature option and actual node v2.0.7.

The UI repo will be updated soon from here : https://github.com/MarcelusCH/insight-ui-btcz

So this issue can be closed.
